language: node_js
node_js:
  - 7.2.1
services:
  - xvfb
env:
  - BROWSER=ChromeCi
  - BROWSER=Firefox

cache:
  directories:
    - node_modules

after_script:
  - npm run coveralls

branches:
  only:
    - master
